services:
  db:
    image: "mcr.microsoft.com/azure-sql-edge"
    user: root
    ports:
      - ${SQL_PORT}:1433
    restart: always
    environment:
      - SA_PASSWORD=${SA_PASSWD}
      - MSSQL_PID=Developer
      - ACCEPT_EULA='Y'
    env_file:
      - ".mygl.env"
    volumes:
      - type: volume
        source: data
        target: /var/opt/mssql

  mygl:
    image: ghcr.io/ashstrahle/mygl:latest
    ports: 
      - ${MYGL_HTTP_PORT}:80
    restart: always
    environment:
      - ConnectionStrings__MyGLContext=Server=db;Database=MyGL;User=sa;Password=${SA_PASSWD};MultipleActiveResultSets=True
    depends_on: 
      - db
volumes:
  data: