version: '3.4'

services:
  db:
   image: "mcr.microsoft.com/azure-sql-edge"
   ports:
      - 1433:1433
   environment:
      - SA_PASSWORD=MyPass@word # PLEASE CHANGE
      - MSSQL_PID=Developer
      - ACCEPT_EULA='Y'

  mygl:
    image: ${DOCKER_REGISTRY-}mygl
    build:
      context: .
      dockerfile: MyGL/Dockerfile
    ports: 
        - "9999:80"
    restart: always
    depends_on: 
        - db