version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/azure-sql-edge"
    user: root
    ports:
       - 1434:1433
    networks:
      default:
        aliases:
          - dbserver
    environment:
       - SA_PASSWORD=mYgLP@s5w0rD # PLEASE CHANGE
       - MSSQL_PID=Developer
       - ACCEPT_EULA='Y'
    volumes:
       - type: volume
         source: data
         target: /var/opt/mssql

  mygl:
    image: ${DOCKER_REGISTRY-}mygl
    build:
      context: .
      dockerfile: MyGL/Dockerfile
    ports: 
       - "9999:80"
    restart: always
    depends_on: 
       - db
volumes:
    data: