name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:
  # Run steps on a matrix of 3 arch/distro combinations
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu-latest

    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: .
          - sudo docker-compose build
          # - docker build . --file Dockerfile --tag MyGL-aarch64:latest
         - docker push ghcr.io/OWNER/MyGL-aarch64:latest
