name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  IMAGE_NAME: MyGL
  IMAGE_TAG: latest
  IMAGE_REGISTRY: quay.io
  IMAGE_NAMESPACE: astrahle

jobs:
  build:
    name: Build and push multi-arch image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Build image 
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAG }}
          archs: aarch64
          dockerfiles: |
            ./MyGL/Dockerfile